// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OSPeConTI.SumariosIERIC.Infrastructure;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SumariosContext))]
    [Migration("20250414181454_segundaMigracion")]
    partial class segundaMigracion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OSPeConTI.SumariosIERIC.Domain.Entities.Acta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadObreros")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaControl")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<Guid?>("LegajoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LegajoId");

                    b.ToTable("Actas", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.SumariosIERIC.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long?>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsCooperativa")
                        .HasColumnType("bit");

                    b.Property<bool>("EstadoActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresa", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.SumariosIERIC.Domain.Entities.Inspector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoIERIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Inspector", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.SumariosIERIC.Domain.Entities.Legajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<long?>("CUIT")
                        .HasColumnType("bigint");

                    b.Property<string>("Estado")
                        .HasPrecision(100)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdentificadorIMR")
                        .HasColumnType("int");

                    b.Property<Guid?>("InspectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LegacyId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAlta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InspectorId");

                    b.ToTable("Legajos", "dbo");
                });

            modelBuilder.Entity("OSPeConTI.SumariosIERIC.Domain.Entities.Acta", b =>
                {
                    b.HasOne("OSPeConTI.SumariosIERIC.Domain.Entities.Legajo", null)
                        .WithMany("Actas")
                        .HasForeignKey("LegajoId");

                    b.OwnsOne("OSPeConTI.SumariosIERIC.Domain.ValueObjects.Location.Direccion", "Domicilio", b1 =>
                        {
                            b1.Property<Guid>("ActaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Barrio")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DomicilioBarrio");

                            b1.Property<string>("Calle")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DomicilioCalle");

                            b1.Property<string>("CodigoPostal")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DomicilioCodigoPostal");

                            b1.Property<string>("Localidad")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DomicilioLocalidad");

                            b1.Property<string>("Numero")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DomicilioNumero");

                            b1.Property<string>("Pais")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DomicilioPais");

                            b1.Property<string>("Provincia")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DomicilioProvincia");

                            b1.HasKey("ActaId");

                            b1.ToTable("Actas", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("ActaId");
                        });

                    b.Navigation("Domicilio");
                });

            modelBuilder.Entity("OSPeConTI.SumariosIERIC.Domain.Entities.Legajo", b =>
                {
                    b.HasOne("OSPeConTI.SumariosIERIC.Domain.Entities.Inspector", "Inspector")
                        .WithMany()
                        .HasForeignKey("InspectorId");

                    b.Navigation("Inspector");
                });

            modelBuilder.Entity("OSPeConTI.SumariosIERIC.Domain.Entities.Legajo", b =>
                {
                    b.Navigation("Actas");
                });
#pragma warning restore 612, 618
        }
    }
}
